// <auto-generated />
using System;
using IndustrialMachinePark.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrialMachinePark.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240612072131_changedToAddDbContextFactory")]
    partial class changedToAddDbContextFactory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndustrialMachinePark.Models.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("LatestData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2dab9f70-f6e8-4df0-b99f-6a93219335e3"),
                            IsOnline = false,
                            LatestData = "The machine is ready to start",
                            Name = "Owen small"
                        },
                        new
                        {
                            Id = new Guid("be822a24-a68e-4658-ac6f-f1b2589434a0"),
                            IsOnline = true,
                            LatestData = "Waiting for ingredients",
                            Name = "Dough Maker"
                        },
                        new
                        {
                            Id = new Guid("bcdacd6c-02ce-4dd8-a82f-d641dfbabf02"),
                            IsOnline = false,
                            LatestData = "Latest rolling: marsipan",
                            Name = "Rolling machine"
                        },
                        new
                        {
                            Id = new Guid("270631ea-5455-44fc-92df-b312304fea2a"),
                            IsOnline = false,
                            LatestData = "Waiting for cream to enter the bowl",
                            Name = "Beater machine"
                        },
                        new
                        {
                            Id = new Guid("8708e4a7-43a8-4f88-965f-fe5b88295d66"),
                            IsOnline = false,
                            LatestData = "The machine is ready to start",
                            Name = "Owen Medium"
                        },
                        new
                        {
                            Id = new Guid("6da5027b-e01e-4538-90df-b4b7dfbb1257"),
                            IsOnline = false,
                            LatestData = "The machine is ready to start",
                            Name = "Owen Large"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
