// <auto-generated />
using System;
using IndustrialMachinePark.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrialMachinePark.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240612130320_changedSeedData")]
    partial class changedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndustrialMachinePark.Models.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("LatestData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5afdc324-e363-4aeb-8e0c-a349eb6ab018"),
                            IsOnline = false,
                            LatestData = "The machine is ready to start",
                            Name = "Owen small"
                        },
                        new
                        {
                            Id = new Guid("f43676c5-4a2e-4a85-9ec5-1c38ba446d66"),
                            IsOnline = true,
                            LatestData = "Waiting for ingredients",
                            Name = "Dough Maker"
                        },
                        new
                        {
                            Id = new Guid("a2ca0ef7-b44f-4408-9034-3526a2a688fb"),
                            IsOnline = false,
                            LatestData = "Latest rolling: marsipan",
                            Name = "Rolling machine"
                        },
                        new
                        {
                            Id = new Guid("596a46ce-43f5-4fab-aef3-6bbec0efe4b3"),
                            IsOnline = false,
                            LatestData = "Waiting for cream to enter the bowl",
                            Name = "Beater machine"
                        },
                        new
                        {
                            Id = new Guid("783fb9b8-fe6a-4acb-90a7-8160ef14bf0d"),
                            IsOnline = true,
                            LatestData = "The machine is ready to start",
                            Name = "Owen Medium"
                        },
                        new
                        {
                            Id = new Guid("327649de-9073-4030-a340-f5549c917702"),
                            IsOnline = true,
                            LatestData = "The machine is ready to start",
                            Name = "Owen Large"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
