// <auto-generated />
using System;
using IndustrialMachinePark.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndustrialMachinePark.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240612071408_seedDataMigration")]
    partial class seedDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndustrialMachinePark.Models.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("LatestData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e69aa2f3-71d2-4823-8c44-c8189a4c3b1b"),
                            IsOnline = false,
                            LatestData = "The machine is ready to start",
                            Name = "Owen small"
                        },
                        new
                        {
                            Id = new Guid("1b90bf7b-ee60-4c03-8434-8968355a76a2"),
                            IsOnline = true,
                            LatestData = "Waiting for ingredients",
                            Name = "Dough Maker"
                        },
                        new
                        {
                            Id = new Guid("5ca63d37-73c8-4d91-bf82-e75fdfdc4f69"),
                            IsOnline = false,
                            LatestData = "Latest rolling: marsipan",
                            Name = "Rolling machine"
                        },
                        new
                        {
                            Id = new Guid("78d1d32f-3342-4b6f-8937-fcd4942505ec"),
                            IsOnline = false,
                            LatestData = "Waiting for cream to enter the bowl",
                            Name = "Beater machine"
                        },
                        new
                        {
                            Id = new Guid("3f939efe-71c2-4454-9f52-bac1efd85359"),
                            IsOnline = false,
                            LatestData = "The machine is ready to start",
                            Name = "Owen Medium"
                        },
                        new
                        {
                            Id = new Guid("a4d5881b-0ded-46de-93f8-4285e27cc6f2"),
                            IsOnline = false,
                            LatestData = "The machine is ready to start",
                            Name = "Owen Large"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
